apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebdeploy
  labels:
    type: mavenwebdeploy
  namespace: test-ns
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mavenwebapplication
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: mavenwebapplication
    spec:
      containers:
      - name: mavencontainer
        image: manikanta1213/java-web-application:TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 200Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mavenhpa
  namespace: test-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mavenwebdeploy
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: mvnsvc
  namespace: test-ns
spec:
  selector:
    app: mavenwebapplication
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30219
